//=========================================================
// src/IoT Supervisor_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================
// This is the internet of trash supervisor
// it has two components: voltage monitoring (because the opi doesn't have it)
// and a watchdog (because stuff crashes all the time and nobody notices)

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "PetitModbus.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// Defines
//-----------------------------------------------------------------------------
#define RESET_P (P1_B1)
#define nLED (P1_B4)

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void)
{
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

// flags
unsigned char t1Flag = 0;

//-----------------------------------------------------------------------------
// the state machine
//-----------------------------------------------------------------------------
//                         VinLow == False
// ┌────────────────────────────────────────────────────────────┐
// │                                                            │
// │                       VinLow Interrupt    ┌────────────┐   │
// │                  ┌───────────────────────►│            │   │
// │                  │                        │    VLow    ├───┘
// │   ┌────────────┐ │                     ┌─►│            │
// │   │            ├─┘                     │  └────────────┘
// ├──►│    Init    │                       │  nReset = False
// │   │            ├─┐     VinLow Interrupt│
// │   └────────────┘ │                     │
// │   nReset = False │                     │
// │                  │                     │  ┌────────────┐
// │                  │ VinLow == False     └──┤            │
// │                  │    2 seconds           │     OK     ├───┐
// │                  └───────────────────────►│            │   │
// │                                           └────────────┘   │
// │                                            nReset = True   │
// │                                           Modbus WDT SMEn  │
// │                 Modbus WDT Timeout                         │
// └────────────────────────────────────────────────────────────┘
// outputs
bool nReset = false; // inverse logic
bool modbusWdtSmEn = false;
// inputs
bool cprif = false; // set outside, cleared here
bool VinCmp = true; // set and cleared before calling
bool modbusWdtExp = false; // set outside, cleared in this SM
uint8_t sCounter = 0;
#define SCOUNTER_ONE_SECOND (125)
// 125 for one second

//-----------------------------------------------------------------------------
// modbus stuff
//-----------------------------------------------------------------------------
// flags
bool modbusRunFlag = false;
typedef enum
{
	Init, VLow, OK
} VinSm_t;

void VinSm(void)
{
	static VinSm_t VinState = Init;

	// determine input state
	VinCmp = CMP0CN0 & CMP0CN0_CPOUT__BMASK;

	// default output states
	nReset = false;
	modbusWdtSmEn = false;

	// transitions
	switch (VinState)
	{
	case Init:
		if (cprif == true || VinCmp == true)
		{
			VinState = VLow;
		}
		else if (sCounter >= SCOUNTER_ONE_SECOND * 2 - 1)
		{
			VinState = OK;
		}
		break;
	case VLow:
		if (VinCmp == false)
		{
			VinState = Init;
		}
		break;
	case OK:
		if (cprif == true || VinCmp == true)
		{
			VinState = VLow;
		}
		else if (modbusWdtExp == true)
		{
			VinState = Init;
		}
		break;
	default:
		VinState = Init;
		break;
	}

	// outputs
	switch (VinState)
	{
	case Init:
		sCounter++;
		break;
	case VLow:
		sCounter = 0;
		break;
	case OK:
		nReset = true;
		modbusWdtSmEn = true;
		sCounter = 0;
		break;
	}

	// output signals
	RESET_P = nReset;
	nLED = nReset;

	// reset flags
	cprif = false;
}

//-----------------------------------------------------------------------------
// Modbus WDT processing from Modbus
//-----------------------------------------------------------------------------
bool mbWDTen = false;
bool mbWDTpet = false;

void mbFlagDet()
{
	if (PetitRegChange)
	{
		// TODO should be a define
		if (PetitRegisters[0] != 0)
		{
			if (PetitRegisters[0] == 0x5A)
			{
				mbWDTpet = true;
			}
			mbWDTen = true;
		}
		PetitRegChange = false;
	}
}

//-----------------------------------------------------------------------------
// Modbus WDT State Machine
//-----------------------------------------------------------------------------
typedef enum
{
	Ini, En, Timeout
} mbWDTsmS_t;


mbWDTsmS_t mbWDTsmS = Ini;
uint16_t mbWDTc = 0;
uint8_t mbWDTcM = 0;

void mbWDTsm (void)
{

	// transitions
	switch(mbWDTsmS)
	{
	case Ini:
		if (mbWDTen && modbusWdtSmEn)
			mbWDTsmS = En;
		break;
	case En:
		if (!mbWDTen || mbWDTpet)
			mbWDTsmS = Init;
		if (mbWDTc >= 15)
			mbWDTsmS = Timeout;
		break;
	case Timeout:
		mbWDTsmS = Init;
		break;
	default:
		mbWDTsmS = Init;
		break;
	}

	// output
	switch(mbWDTsmS)
	{
	case Ini:
		mbWDTc = 0;
		mbWDTcM = 0;
		break;
	case En:
		mbWDTc++;
		if (mbWDTc >= 7500)
			mbWDTcM++;
		// yass
		PetitRegisters[0] = 0xEA55;
		break;
	case Timeout:
		// bite
		PetitRegisters[0] = 0xB17E;
		mbWDTen = false;
		modbusWdtExp = true;
		break;
	}
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------

int main(void)
{
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

	while (1)
	{
		if (t1Flag)
		{
			t1Flag = 0;
			ProcessPetitModbus();
			mbFlagDet();
		}

		// put MCU in idle mode to save power
		PCON0 |= PCON0_IDLE__IDLE;
		// $[Generated Run-time code]
		// [Generated Run-time code]$
	}
}
