//=========================================================
// src/IoT Supervisor_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================
// This is the internet of trash supervisor
// it has two components: voltage monitoring (because the opi doesn't have it)
// and a watchdog (because stuff crashes all the time and nobody notices)

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "debugpins.h"
#include "PetitModbus.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// Defines
//-----------------------------------------------------------------------------
#define RESET_P (P1_B1)
#define nLED (P1_B4)
static const int C_MB_WD_COUNT2MIN = 7500;
static const int C_MB_WD_TIMEOUT = 15;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enabled by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void)
{
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

// flags
volatile union
{
	// vector access
	struct
	{
		uint8_t t1Flag :1;
		uint8_t vinSmFlag :1;
		uint8_t WDTsmFlag :1;
	} v;
	// byte access
	uint8_t b;
} exec_flags;

//-----------------------------------------------------------------------------
// the state machine
//-----------------------------------------------------------------------------
//                         VinLow == False
// ┌────────────────────────────────────────────────────────────┐
// │                                                            │
// │                       VinLow Interrupt    ┌────────────┐   │
// │                  ┌───────────────────────►│            │   │
// │                  │                        │    VLow    ├───┘
// │   ┌────────────┐ │                     ┌─►│            │
// │   │            ├─┘                     │  └────────────┘
// ├──►│    Init    │                       │  nReset = False
// │   │            ├─┐     VinLow Interrupt│
// │   └────────────┘ │                     │
// │   nReset = False │                     │
// │                  │                     │  ┌────────────┐
// │                  │ VinLow == False     └──┤            │
// │                  │    2 seconds           │     OK     ├───┐
// │                  └───────────────────────►│            │   │
// │                                           └────────────┘   │
// │                                            nReset = True   │
// │                                           Modbus WDT SMEn  │
// │                 Modbus WDT Timeout                         │
// └────────────────────────────────────────────────────────────┘
// == outputs ==
bool nReset = false; // inverse logic
bool modbusWdtSmEn = false;
// == inputs ==
// comparator input flag
bool cprif = false; // set outside, cleared here
// modbus watchdog expired
bool modbusWdtExp = false; // set outside, cleared in this SM

// == constants ==
#define SCOUNTER_ONE_SECOND (125)
// 125 for one second

//-----------------------------------------------------------------------------
// modbus stuff
//-----------------------------------------------------------------------------
// flags
bool modbusRunFlag = false;
typedef enum
{
	Init, VLow, OK
} VinSm_t;

void VinSm(void)
{
	// static variables
	static VinSm_t VinState = Init;
	static uint8_t sCounter = 0;

	// determine input state
	bool VinCmp = CMP0CN0 & CMP0CN0_CPOUT__BMASK;

	// default output states
	nReset = false;
	modbusWdtSmEn = false;

	// transitions
	switch (VinState)
	{
	case Init:
		if (cprif == true || VinCmp == true)
		{
			VinState = VLow;
		}
		else if (sCounter >= SCOUNTER_ONE_SECOND * 2 - 1)
		{
			VinState = OK;
		}
		break;
	case VLow:
		if (VinCmp == false)
		{
			VinState = Init;
		}
		break;
	case OK:
		if (cprif == true || VinCmp == true)
		{
			VinState = VLow;
		}
		else if (modbusWdtExp == true)
		{
			VinState = Init;
		}
		break;
	default:
		VinState = Init;
		break;
	}

	// outputs
	switch (VinState)
	{
	case Init:
		sCounter++;
		modbusWdtExp = false;
		break;
	case VLow:
		sCounter = 0;
		PetitRegisters[0] = 0x5010; // lo (w)
		break;
	case OK:
		nReset = true;
		modbusWdtSmEn = true;
		sCounter = 0;
		break;
	}

	// output signals
	RESET_P = nReset;
	nLED = nReset;

	// reset flags
	cprif = false;
}

//-----------------------------------------------------------------------------
// Modbus WDT processing from Modbus
//-----------------------------------------------------------------------------
bool mbWDTen = false;
bool mbWDTpet = false;

// todo: handshake for disable
void mbFlagDet()
{
	if (PetitRegChange)
	{
		PetitRegChange = false;
		// TODO should be a define
		if (PetitRegisters[1] != 0)
		{
			if (PetitRegisters[1] == 0x5A)
			{
				mbWDTpet = true;
				mbWDTen = true;
				PetitRegisters[1] = 0;
			}
			if (PetitRegisters[1] == 0xA5)
			{
				mbWDTen = false;
			}
		}
	}
}

//-----------------------------------------------------------------------------
// Modbus WDT State Machine
//-----------------------------------------------------------------------------
typedef enum
{
	Ini, En, Timeout
} mbWDTsmS_t; // modbus watchdog timer state machine states _ type

void mbWDTsm(void)
{
	// statics
	static mbWDTsmS_t mbWDTsmS = Ini;
	static uint16_t mbWDTc = 0;		// modbus watchdog timer counter
	static uint8_t mbWDTcM = 0;		// modbus watchdog timer counter (minute)

	// transitions
	switch (mbWDTsmS)
	{
	case Ini:
		if (mbWDTen && modbusWdtSmEn)
			mbWDTsmS = En;
		break;
	case En:
		if (!mbWDTen || mbWDTpet)
			mbWDTsmS = Init;
		if (mbWDTcM >= C_MB_WD_TIMEOUT)
			mbWDTsmS = Timeout;
		break;
	case Timeout:
		mbWDTsmS = Init;
		break;
	default:
		mbWDTsmS = Init;
		break;
	}

	// output
	switch (mbWDTsmS)
	{
	case Ini:
		mbWDTc = 0;
		mbWDTcM = 0;
		break;
	case En:
		mbWDTc++;
		if (mbWDTc >= C_MB_WD_COUNT2MIN)
			mbWDTcM++;
		PetitRegisters[0] = 0xEA55; // yass
		break;
	case Timeout:
		PetitRegisters[0] = 0xB17E; // bite
		mbWDTen = false;
		modbusWdtExp = true;
		break;
	}

	mbWDTpet = false;
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------

int main(void)
{
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();
#if DEBUG
	// enter debugmode to get the pins working
	enter_DebugMode_from_DefaultMode();
#endif

	while (1)
	{
		if (exec_flags.v.t1Flag)
		{
			exec_flags.v.t1Flag = 0;

			PETIT_PROCESS_ON();

			ProcessPetitModbus();
			mbFlagDet();

			PETIT_PROCESS_OFF();
		}

		if (exec_flags.v.vinSmFlag)
		{
			exec_flags.v.vinSmFlag = 0;
			VinSm();
		}

		if (exec_flags.v.WDTsmFlag)
		{
			exec_flags.v.WDTsmFlag = 0;
			mbWDTsm();
		}

		//     idle mode taken out because of some race condition that keeps
		// being reached.

		// $[Generated Run-time code]
		// [Generated Run-time code]$
	}
}
